# Generated by Django 6.0.7 on 2026-08-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=100)),
                ('prioridade', models.CharField(choices=[('URGENTE', 'URGENTE'), ('MEDIA', 'MEDIA'), ('BAIXA', 'BAIXA')], max_length=7)),
                ('tipo', models.CharField(choices=[('HARDWARE', 'HARDWARE'), ('SOFTWARE', 'SOFTWARE')], max_length=8)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
