# Generated by Django 6.0.7 on 2026-08-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='resolvido',
            field=models.BooleanField(default=False),
        ),
    ]
